


app.security.permits-all=false
app.jwt.secret=mySuperSecretKeyForJwtSigningThatIsAtLeast32Bytes!
app.jwt.expiration=3600000

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.integration.file.remote.session=DEBUG

spring.config.activate.on-profile=dev


# ftp Configuration
ftp.host=localhost
ftp.port=21
ftp.username=spring
ftp.password=spring
ftp.remote-directory=/log-data
ftp.local-directory=c:/temp/ftp-test/downloads
ftp.passive-mode=true

# Logging Configuration
logging.level.org.springframework.integration=DEBUG
logging.level.com.jcraft.jsch=DEBUG