spring.config.activate.on-profile=prod

app.security.permits-all=false
logging.level.org.springframework.web=INFO


# ftp Configuration
ftp.host=localhost
ftp.port=21
ftp.username=ftpuser
ftp.password=ftppassword

# ftp Directories
ftp.remote-directory=/uploads
ftp.local-directory=./ftp-downloads

# ftp Connection Settings
ftp.timeout=30000

# Logging Configuration
logging.level.org.springframework.integration=INFO
logging.level.com.jcraft.jsch=INFO